server:
  port: 8443

spring:
  # api gson mapper setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    converters:
      preferred-json-mapper: gson
  # datasource: 상세 설정은 mariadb profile 참조
  profiles:
    include:
    - mariadb
    - es
  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
        jdbc:
          batch_size: 500
  # es
  data:
    elasticsearch:
      repositories:
        enabled: true
# spring doc (swagger)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # path -> query > body -> response
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

logging:
  level:
    co.elastic.clients: DEBUG