server:
  port: 8080

spring:
  # api gson mapper setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    converters:
      preferred-json-mapper: gson
  # datasource: 상세 설정은 mariadb profile 참조
  profiles:
    include:
    - mariadb
    - es
  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
        jdbc:
          batch_size: 500